#!/usr/bin/env bash

git stash
branchname=$(git symbolic-ref --short HEAD)

git checkout master
git fetch origin master
git rebase origin/master

git checkout $branchname
git rebase master

git stash pop
